services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - GROQ_API_KEY_1=${GROQ_API_KEY_1}
      - GROQ_API_KEY_2=${GROQ_API_KEY_2}
      - FIREBASE_BUCKET=${FIREBASE_BUCKET}
      - FIREBASE_CREDENTIALS=${FIREBASE_CREDENTIALS}
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    depends_on:
      - backend
    restart: always